version: "3.8"

services:
  mongodb:
    image: mongo:6-jammy
    restart: always
    tmpfs:
      - /data/db
    ports:
      - '27017:27017'

  Elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'

  Logstash:
    image: logstash:7.17.10
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  Kibana:
    image: kibana:7.17.10
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch