# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: curso-spring-boot
  labels:
    # label your deployment
    app: curso-spring-boot
spec:
  # The number of pods/replicas to run
  replicas: 1
  selector:
    matchLabels:
      # selector to match the pod
      app: curso-spring-boot-app
  template:
    metadata:
      labels:
        # label your pod
        app: curso-spring-boot-app
    spec:
      containers:
        # Add the container name for Kubernetes
        - name: curso-spring-boot-app
          # Add the local image name
          image: curso-spring-boot:latest
          # never pull the image policy
          imagePullPolicy: Never
          ports:
            # port for running the container
            - containerPort: 8080
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: curso-spring-boot-service
spec:
  selector:
    # selector that matches the pod
    app: curso-spring-boot-service-app
  # type of service
  type: LoadBalancer
  ports:
    - protocol: TCP
      # port for exposing the service
      port: 8080
      # portfor exposing the pod
      targetPort: 8080
      # port for exposing the node
      nodePort: 31110